---
title: "pure_opr"
format: html
---

# Pure OPR

```{r}
library(scoutR)
library(tidyverse)
raw <- read.csv("../shinyapp/data/test_data/data.csv")
schedule <- read.csv("../shinyapp/data/test_data/schedule.csv")
unique_teams <- unique(raw$team)[order(unique(raw$team))]
capacity_list <- sample(20:60, size = length(unique_teams), replace = TRUE)

data <- raw |>
    rowwise() |>
    mutate(
        total_balls = sum(
            auto_cap*auto_acc*capacity_list[team == unique_teams],
            tele_cap1*tele_acc1*capacity_list[team == unique_teams],
            tele_cap2*tele_acc2*capacity_list[team == unique_teams],
            tele_cap3*tele_acc3*capacity_list[team == unique_teams],
            tele_cap4*tele_acc4*capacity_list[team == unique_teams],
            tele_cap5*tele_acc5*capacity_list[team == unique_teams],
            tele_cap6*tele_acc6*capacity_list[team == unique_teams],
            tele_cap7*tele_acc7*capacity_list[team == unique_teams],
            tele_cap8*tele_acc8*capacity_list[team == unique_teams]
        ),
    ) |>
    select(match, team, total_balls) |>
    mutate(
        alliance_color = factor(ifelse(
            (team %in% c(schedule[match,]$R1, schedule[match,]$R2, schedule[match,]$R3)),
            "red", "blue"), levels = c("red", "blue"))
    )
    
unique_teams <- sort(unique(data$team))
    
lineups <- matrix(0, nrow = length(unique(data$match))*2, ncol = length(unique_teams))
colnames(lineups) <- unique_teams
for (i in 1:nrow(lineups)) {
    teams <- filter(data, match == ceiling(i/2), alliance_color == ifelse(i %% 2, "red", "blue"))
    lineups[i, as.character(teams$team)] = 1
}
        
data <- data |>
    group_by(match, alliance_color) |>
    summarize(
        total_balls = sum(total_balls)
        )
    
lineups <- as.data.frame(lineups)
lineups$score = data$total_balls

w <- rep(1, nrow(lineups))
opr <- lm(score ~ 0 + ., data = lineups, weights = w)$coefficients
a <- sort(opr)
```

```{r}
library(scoutR)
data <- read.csv("data.csv")
opr <- lm(score ~ 0 + ., data = data, weights = rep(1, nrow(data)))$coefficients
opr <- opr[order(as.integer(gsub("`", "", names(opr))))]
pridge_lambda_cv(
    data[1:40], 
    unlist(data[41]),
    rep(mean(opr), 40),
    1:100
    )
```

\
